RobotLocomotion/drake-iiwa-driver

.gitmodules
CMakeLists.txt
README.md
kuka-driver/CMakeLists.txt

- remove cmake external project and externals
- supports out of source builds

new cmake build system

---

CMakeLists.txt
README.md
fri_udp_connection_file_descriptor.diff
kuka-driver/CMakeLists.txt
kuka-driver/kuka_driver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/2)

Add the ability to control multiple arms

---

kuka-driver/CMakeLists.txt
kuka-driver/kuka_driver.cc

This project requires some lcm types from drake but that dependency was not explicit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/4)

Find drake lcmtypes interface library

---

README.md

@sammy-tri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/5)

Add documentation on how to install software options

---

kuka-driver/BUILD
kuka-driver/kuka_driver.cc
kuka-driver/low_pass_filter.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/11)

adding a low pass filter for joint velocity.

---

kuka-driver/kuka_driver.cc

You can pass the threshold by adding -ext_trq_limit flag in the command line. The threshold is then scaled independently for each joint and used to check against the external torque field reported back from kuka's controller. Once any external torque exceeds its threshold, the driver throws an exception and dies.
The default threshold is 60, and the scale is [1, 1, 1, 0.5, 0.2, 0.2, 0.1]. The scale cannot be modified in the command line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/12)

add a external torque limit check.

---

kuka-driver/kuka_driver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/16)

Fix to build against Sunrise 1.13 or 1.11 

---

kuka-driver/sunrise_1.11/DrakeFRITorqueDriver.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/18)

Use joint impedance mode with the torque driver

---

kuka-driver/kuka_driver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/17)

Process the LCM command before dispatching to the FRI event handler

---

kuka-driver/CMakeLists.txt
kuka-driver/kuka_driver.cc

Only proposing merge into `master-rlg` branch but @sammy-tri maybe also useful for you
This seems to essentially solve the latency issue we were previously having with our robot state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/13)

Directly publish /joint_state in ROS from kuka_driver.cc

---

tools/kuka-fri.BUILD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/20)

Modify the FRI build so that it builds in the sandbox 

---

kuka-driver/sunrise_1.11/DrakeFRITorqueDriver.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/21)

switch to torque driver from tri master branch

---

kuka-driver/kuka_driver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/22)

hack to get external torque measurements

---

kuka-driver/kuka_driver.cc

Don't keep trying to move the robot if we're entering command state for the second time.
It's not likely to go well if our controller is streaming an open loop plan at us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/23)

Inhibit motion when re-entering command state

---

tools/kuka-fri.BUILD

Also, run buildifier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/25)

Disable warnings in kuka-fri compilation 

---

README.md
tools/kuka-fri.BUILD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/35)

Add better FRI compatabilty and update build instructions

---

kuka-driver/kuka_driver.cc

Fixes #33
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/37)

Added a guard between the first status message and the first command message.

---

WORKSPACE
kuka-driver/BUILD.bazel
kuka-driver/kuka_driver.cc

While working on #44
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/45)

Fix minor lint issues; enable lint on cc file

---

kuka-driver/kuka_driver.cc
kuka-driver/sunrise_1.14/DrakeFRITorqueOnlyDriver.java

Tested on hardware for non-zero "hold" gains and zero "hold" gains (reproducing gravity comp demo)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-iiwa-driver/44)

[kuka_driver] Add --torque_only flag

---

WORKSPACE

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/46)

Bump drake version to get support for bazel 6.0.0.

---

kuka-driver/kuka_driver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/47)

Activate friction compensation in torque_only mode

---

kuka-driver/kuka_driver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/48)

Added velocity filter as a command line argument

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-iiwa-driver/49)

Add gflags install to README
